### ISSUE TITLE
tnn init failed

### ISSUE THREAD

**Issue by sychou11** [lmf12/blog-demo#10]
按照步骤来的，运行后
self.networkInstance = self.network->CreateInst(networkConfig, status)  这行出现以下报错：TNN/source/tnn/interpreter/tnn/model_interpreter.cc][Line 361] tnnmodel is invalid, maybe you should upgrade TNN

请问如何解决呢？

**Comment by lmf12** [comment]
TNN 版本与模型版本存在匹配问题，最新版本与模型不一定匹配，已经上传了可以运行的编译好的版本。
